# Site settings
title: Abracodeabra
header-img: img/home-bg.png
email: aellonkrider@gmail.com
copyright_name: aellonk
description: > # this means to ignore newlines until "baseurl:"
  magic tricks for code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Aellon
github_username:  aellonk
learn_profile: aellonk
email_username: aellonkrider@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
